### ISSUE TITLE
TSaslClientTransport._send_message cannot concat str to bytes

### ISSUE THREAD

**Issue by GrierPhillips** [cloudera/thrift_sasl#14]
When connecting to Hive through Impyla with mechanism 'GSSAPI' the `_send_message` method fails when trying to concatenate the string 'GSSAPI' to the header bytes. The solution for this (widely spread across the web) is to insert a type check and conversion for the `body`  argument as follows:

```
  def _send_message(self, status, body):
    header = struct.pack(">BI", status, len(body))
    if isinstance(body, str):
        body = body.encode()
    self._trans.write(header + body)
    self._trans.flush()
```
It would seem based on the `__init__` docstring that the expected behavior is to accept strings for the `mechanism` argument.  However, I'm not exactly sure how this is intended to work without converting to bytes when it is passed to `_send_message`. 

We would like to use thrift_sasl in a production system, but would rather rely on the cloudera distribution than an internally maintained distribution for just 2 lines of code. Would it be possible to include this change in any upcoming releases?

**Comment by zhaobaohua** [comment]
Have you solved the problem？
i hava the same problem
`D:\Anaconda3\envs\py35\lib\site-packages\thrift_sasl\__init__.py in _send_message(self, status, body)
     92   def _send_message(self, status, body):
     93     header = struct.pack(">BI", status, len(body))
---> 94     if isinstance(body, str):
     95       body = body.encode()
     96     self._trans.write(header + body)

TypeError: can't concat str to bytes

`

**Comment by dknupp** [comment]
0.4.1 is available on https://pypi.org/project/thrift-sasl/, and should contain not have this issue.
