### ISSUE TITLE
New release in pip

### ISSUE THREAD

**Issue by flolas** [cloudera/thrift_sasl#20]
Hi!

It would be nice to have a new release in pip with the changes of #14 Merged PR! Currently the latest version in pip (0.4a1) doesn't works with Python 3.x because of that!

Thanks!

Cheers
Felipe!

**Comment by flolas** [comment]
#14

**Comment by dknupp** [comment]
Thanks for the comment @flolas -- sadly, while the fix for issue #14 made the library work with python 3.x, it also broke backwards compatibility with python 2.x. Pull request #19 is open to address that.

**Comment by dknupp** [comment]
0.4.1 available on https://pypi.org/project/thrift-sasl/
