### ISSUE TITLE
Frames are not fully buffered when used with thriftpy / thriftpy2

### ISSUE THREAD

**Issue by packet23** [cloudera/thrift_sasl#31]
The buffering issue that had been improved as part of #22 and #23 is still present when thrift_sasl is used together with thriftpy / thriftpy2 as is the default for impyla on Python 3.x. As a consequence, running a simple test query can cause the client to become stuck.

**Comment by neilgluent** [comment]
The proposed fix for this issue also appears to fix issue 28: https://github.com/cloudera/thrift_sasl/issues/28

I've commented on 28 regarding this: https://github.com/cloudera/thrift_sasl/issues/28#issuecomment-788859899

**Comment by Maxsparrow** [comment]
Thanks for the comment @neilgluent - I tested the fix on our setup, and I can confirm it also fixes issue #28 for us.

**Comment by danielewood** [comment]
Thanks @packet23 , this fixes #28 for us. I now can do queries that result in over 20MB of returned data with no issue.
