### ISSUE TITLE
Problem when installing on Windows

### ISSUE THREAD

**Issue by ZuluagaSD** [cloudera/thrift_sasl#4]
For some reason I can not do `pip install thrift_sasl` because I get an error:

(D:\Archivos de programa\Miniconda2\envs\anaconda) C:\Users\DANISUAR>pip install
 thrift_sasl
Collecting thrift_sasl
Collecting sasl>=0.2.1 (from thrift_sasl)
  Using cached sasl-0.2.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): thrift in d:\archivos
de programa\miniconda2\envs\anaconda\lib\site-packages (from thrift_sasl)
Requirement already satisfied (use --upgrade to upgrade): six in d:\archivos de
programa\miniconda2\envs\anaconda\lib\site-packages (from sasl>=0.2.1->thrift_sa
sl)
Building wheels for collected packages: sasl
  Running setup.py bdist_wheel for sasl ... error
  Complete output from command "D:\Archivos de programa\Miniconda2\envs\anaconda
\python.exe" -u -c "import setuptools, tokenize;**file**='c:\users\danisuar\a
ppdata\local\temp\pip-build-hwjvfh\sasl\setup.py';exec(compile(getattr(toke
nize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))"
bdist_wheel -d c:\users\danisuar\appdata\local\temp\tmp1pkrkdpip-wheel- --python
-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\sasl
  copying sasl__init__.py -> build\lib.win-amd64-2.7\sasl
  running egg_info
  writing requirements to sasl.egg-info\requires.txt
  writing sasl.egg-info\PKG-INFO
  writing top-level names to sasl.egg-info\top_level.txt
  writing dependency_links to sasl.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'sasl.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'sasl.egg-info\SOURCES.txt'
  copying sasl\saslwrapper.cpp -> build\lib.win-amd64-2.7\sasl
  copying sasl\saslwrapper.h -> build\lib.win-amd64-2.7\sasl
  copying sasl\saslwrapper.pyx -> build\lib.win-amd64-2.7\sasl
  running build_ext
  building 'sasl.saslwrapper' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\sasl
  C:\Users\DANISUAR\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pytho
n\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isasl "-ID:\Arch
ivos de programa\Miniconda2\envs\anaconda\include" "-ID:\Archivos de programa\Mi
niconda2\envs\anaconda\PC" /Tpsasl/saslwrapper.cpp /Fobuild\temp.win-amd64-2.7\R
elease\sasl/saslwrapper.obj
  saslwrapper.cpp
  sasl/saslwrapper.cpp(247) : fatal error C1083: Cannot open include file: 'stdi
nt.h': No such file or directory
  error: command 'C:\Users\DANISUAR\AppData\Local\Programs\Common\Microso
ft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe' failed with exit status
2

---

  Failed building wheel for sasl
  Running setup.py clean for sasl
Failed to build sasl
Installing collected packages: sasl, thrift-sasl
  Found existing installation: sasl 0.1.3
    Uninstalling sasl-0.1.3:
      Successfully uninstalled sasl-0.1.3
  Running setup.py install for sasl ... error
    Complete output from command "D:\Archivos de programa\Miniconda2\envs\anacon
da\python.exe" -u -c "import setuptools, tokenize;**file**='c:\users\danisuar\
\appdata\local\temp\pip-build-hwjvfh\sasl\setup.py';exec(compile(getattr(to
kenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))
" install --record c:\users\danisuar\appdata\local\temp\pip-rhjy84-record\instal
l-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\sasl
    copying sasl__init__.py -> build\lib.win-amd64-2.7\sasl
    running egg_info
    writing requirements to sasl.egg-info\requires.txt
    writing sasl.egg-info\PKG-INFO
    writing top-level names to sasl.egg-info\top_level.txt
    writing dependency_links to sasl.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'sasl.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sasl.egg-info\SOURCES.txt'
copying sasl\saslwrapper.cpp -> build\lib.win-amd64-2.7\sasl
copying sasl\saslwrapper.h -> build\lib.win-amd64-2.7\sasl
copying sasl\saslwrapper.pyx -> build\lib.win-amd64-2.7\sasl
running build_ext
building 'sasl.saslwrapper' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\sasl
C:\Users\DANISUAR\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pyt
```

hon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isasl "-ID:\Ar
chivos de programa\Miniconda2\envs\anaconda\include" "-ID:\Archivos de programa\
Miniconda2\envs\anaconda\PC" /Tpsasl/saslwrapper.cpp /Fobuild\temp.win-amd64-2.7
\Release\sasl/saslwrapper.obj
    saslwrapper.cpp
    sasl/saslwrapper.cpp(247) : fatal error C1083: Cannot open include file: 'st
dint.h': No such file or directory
    error: command 'C:\Users\DANISUAR\AppData\Local\Programs\Common\Micro
soft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe' failed with exit statu
s 2

```
----------------------------------------
```

  Rolling back uninstall of sasl
Command ""D:\Archivos de programa\Miniconda2\envs\anaconda\python.exe" -u -c "im
port setuptools, tokenize;**file**='c:\users\danisuar\appdata\local\temp\p
ip-build-hwjvfh\sasl\setup.py';exec(compile(getattr(tokenize, 'open', open)(__
file__).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\us
ers\danisuar\appdata\local\temp\pip-rhjy84-record\install-record.txt --single-ve
rsion-externally-managed --compile" failed with error code 1 in c:\users\danisua
r\appdata\local\temp\pip-build-hwjvfh\sasl\

**Comment by theviajero** [comment]
Searching for a solution and Daniel was already here . . .
