### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mrfuxi** [cloudera/thrift_sasl#8]
Can there be a new release?
At this point I have to install from straight from git to avoid issues like

```
    216     def readI32(self):
--> 217         buff = self.trans.readAll(4)
    218         val, = unpack('!i', buff)
    219         return val

AttributeError: 'TSaslClientTransport' object has no attribute 'readAll'
```

I guess there are similar issues around since [dropbox/PyHive](https://github.com/dropbox/PyHive) repo has that in [req file](https://github.com/dropbox/PyHive/blob/master/dev_requirements.txt):
```
git+https://github.com/cloudera/thrift_sasl  # Using master branch in order to get Python 3 SASL patches
```

With latest commit works fine,
Thanks

**Comment by mdeguzis** [comment]
Hows your experience with pypi's thift_sasl? I am considering using this one.

**Comment by mdeguzis** [comment]
One thing I struggle with is connecting to our HiveServer2 over SSL. Glad the source here is more fresh at least than their release on pypi.

**Comment by cartershanklin** [comment]
Running into similar problems, a new release seems like it will make thrift_sasl work with Python 3.

**Comment by mrfuxi** [comment]
using `thrift_sasl==0.3.0` solves the issue for me now
