### ISSUE TITLE
PyPI currently hosts older version

### ISSUE THREAD

**Issue by nonsleepr** [cloudera/thrift_sasl#9]
This repo hosts newer version of the code which doesn't depend on `thriftpy`. Could you publish it to PyPI?

**Comment by vijayk** [comment]
0.2.1 version available on PyPI is old. Please publish a latest release to PyPi repo. 
Connecting to HiveServer2 ends up in SSL error while picking the latest code FIXES the SSL error on Py34.

Releasing a latest version with latest code to pypi is required.

**Comment by wesm** [comment]
Just released thrift_sasl 0.3.0: https://pypi.python.org/pypi/thrift_sasl
